package com.pelayo.integrations.sisnetvad.utils

public class SisnetVadConstants {
    public static final String sisnetVadBasePath  = "sisnetvad"
    public static final String sisnetVadSourceDir = "${sisnetVadBasePath}/src"
    public static final String sisnetVadConfigDir = "${sisnetVadBasePath}/config"
    public static final String sisnetVadArtifact  = "${sisnetVadBasePath}/artifact"

    public static final Map artifacts = [
        "SISNETVADWAR":"WebSISnetPelayoVAD"
        ]
    public static Map ENTORNOS_SISNETVAD=[
        "INTG":[
            "NAME":"Integración",
            "URL":'ssh://bitbucket-lab.pelayo.com:7999/vad/websisnetpelayovad.git',
            "GIT_BRANCH":"env/01-INTG",
            "SERVERS":[
                ["NAME":"sisnetvaddesa","IP":"sisnetvaddesa","USER":"operador"]
            ],
            "ARTIFACTREPOSITORY":[
                "URL":"http://192.6.3.179:8081/",
                "REPOSITORY":"repository/pelayo-sisnet-snapshots/",
                "GROUPID":"org.pelayo"
            ],
            "FILESPATHDESTINY":"/netijam/WorkSISnet/Configuracion/Calcular",
            "FILESCONFIG":[
                "jobparms.xml",
                "sisnet_sismemory.xml",
                "SISnetServiciosExternos.xml",
                "sisnet.xml",
                "sisnet_rutas_publicadas.xml",
                "sisnet_multis.xml",
                "aplicaciones.xml",
                "sisnet_entorno.xml",
                "sisnet_liferay.xml",
                "sisnet_sms.xml",
                "SISnetRESTConfig.xml",
                "SISnetSocketConfig.xml"
            ],
            "SISNETCONFIGGIT":[
                "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad.git',
	            "BRANCH": 'master'
            ]
        ],
        "ACPT":[
            "NAME":"Aceptación",
            "URL":'ssh://bitbucket-lab.pelayo.com:7999/vad/websisnetpelayovad.git',
            "VERSION_PATH":"03-ACPT",
            "GIT_BRANCH":"env/02-ACPT",
            "SERVERS":[
                ["NAME":"portal-acpt","IP":"sisnetvadacpt","USER":"operador"]
            ],
            "ARTIFACTREPOSITORY":[
                "URL":"http://192.6.3.179:8081/",
                "REPOSITORY":"repository/pelayo-sisnet-snapshots/",
                "GROUPID":"org.pelayo"
            ],
            "FILESPATHDESTINY":"/netijam/WorkSISnet/Configuracion/Calcular",
            "FILESCONFIG":[
                "jobparms.xml",
                "sisnet_sismemory.xml",
                "SISnetServiciosExternos.xml",
                "sisnet.xml",
                "sisnet_rutas_publicadas.xml",
                "sisnet_multis.xml",
                "aplicaciones.xml",
                "sisnet_entorno.xml",
                "sisnet_liferay.xml",
                "sisnet_sms.xml",
                "SISnetRESTConfig.xml",
                "SISnetSocketConfig.xml"
            ],
            "SISNETCONFIGGIT":[
                "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad.git',
	            "BRANCH": 'master'
            ]
        ],
        "PREP":[
            "NAME":"Preproducción",
            "URL":'ssh://bitbucket-lab.pelayo.com:7999/vad/websisnetpelayovad.git',
            "GIT_BRANCH":"env/03-PREP",
            "SERVERS":[
                ["NAME":"portal-pre","IP":"sisnetvadpre1","USER":"operador"],
                ["NAME":"sisnetvadpre2","IP":"sisnetvadpre2","USER":"operador"]
            ],
            "ARTIFACTREPOSITORY":[
                "URL":"http://192.6.3.179:8081/",
                "REPOSITORY":"repository/pelayo-sisnet-snapshots/",
                "GROUPID":"org.pelayo"
            ],
            "FILESPATHDESTINY":"/netijam/WorkSISnet/Configuracion/Calcular",
            "FILESCONFIG":[
                "jobparms.xml",
                "sisnet_sismemory.xml",
                "SISnetServiciosExternos.xml",
                "sisnet.xml",
                "sisnet_rutas_publicadas.xml",
                "sisnet_multis.xml",
                "aplicaciones.xml",
                "sisnet_entorno.xml",
                "sisnet_liferay.xml",
                "sisnet_sms.xml",
                "SISnetRESTConfig.xml",
                "SISnetSocketConfig.xml"
            ],
            "SISNETCONFIGGIT":[
                "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad-pro.git',
	            "BRANCH": 'master'
            ]
        ],
        "PROD":[
            "NAME":"Producción",
            "URL":'ssh://bitbucket-lab.pelayo.com:7999/vad/websisnetpelayovad.git',
            "GIT_BRANCH":"master",
            "SERVERS":[
                ["NAME":"sisnetvadpro1","IP":"sisnetvadpro1","USER":"operador"],
                ["NAME":"sisnetvadpro2","IP":"sisnetvadpro2","USER":"operador"]
            ],
            "ARTIFACTREPOSITORY":[
                "URL":"http://192.6.3.179:8081/",
                "REPOSITORY":"repository/pelayo-sisnet-releases/",
                "GROUPID":"org.pelayo"
            ],
            "FILESPATHDESTINY":"/netijam/WorkSISnet/Configuracion/Calcular",
            "FILESCONFIG":[
                "jobparms.xml",
                "sisnet_sismemory.xml",
                "SISnetServiciosExternos.xml",
                "sisnet.xml",
                "sisnet_rutas_publicadas.xml",
                "sisnet_multis.xml",
                "aplicaciones.xml",
                "sisnet_entorno.xml",
                "sisnet_liferay.xml",
                "sisnet_sms.xml",
                "SISnetRESTConfig.xml",
                "SISnetSocketConfig.xml"
            ],
            "SISNETCONFIGGIT":[
                "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad-pro.git',
	            "BRANCH": 'master'
            ]
        ]
    ]
    public static Map ENTORNOS_SISNETVADCONFIG=[
        "MASTER":[
            "NAME":"Configuracion",
            "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad.git',
            "GIT_BRANCH":"*master",
            "PATH_POM":[
                "INTG":"maven/02-INTG",
                "ACPT":"maven/03-ACPT",
                "PREP":"maven/04-PREP",
                "PROD":"maven/05-PROD"
            ],
            "PATH_CONFIG":[
                "INTG":"producto/02-INTG",
                "ACPT":"producto/03-ACPT",
                "PREP":"producto/04-PREP",
                "PROD":"producto/05-PROD"
            ]
        ],
        "DEVELOP":[
            "NAME":"Configuracion Develop",
            "URL":'ssh://git@bitbucket-lab.pelayo.com:7999/snt/config-sisnetvad.git',
            "GIT_BRANCH":"*develop",
            "PATH_CONFIG":[
                "INTG":"maven/02-INTG",
                "ACPT":"maven/03-ACPT",
                "PREP":"maven/04-PREP",
                "PROD":"maven/05-PROD"
            ],
            "PATH_CONFIG":[
                "INTG":"producto/02-INTG",
                "ACPT":"producto/03-ACPT",
                "PREP":"producto/04-PREP",
                "PROD":"producto/05-PROD"
            ]
        ]
    ]
}